spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: primary
      strict: false
      datasource:
        primary:
          driver-class-name: dm.jdbc.driver.DmDriver
          url: jdbc:dm://118.193.126.254:5236/INTELLIGENT_OFFICE?schema=INTELLIGENT_CONTENT&encoding=UTF-8
          username: SYSDBA
          password: Sysdba@123
  cloud:
    nacos:
      discovery:
#        enabled: false
#        instance-enabled: false
        server-addr: 101.52.216.178:8848
        username: nacos
        password: yyccYOUyun
  #        server-addr: 10.10.93.81:8848
#        # gateway 与对应的后端服务应该在相同的namespace下
#        namespace: 33125179-fe3d-4c48-84f9-157e298d40b4
#        username: nacos
#        password: nacos@ttknoa
#      config:
##        server-addr: localhost:8848
#        server-addr: 10.10.93.81:8848
#        file-extension: yaml
#        namespace: 33125179-fe3d-4c48-84f9-157e298d40b4
#        username: nacos
#        password: nacos@ttknoa
  data:
    redis:
      host: 101.52.216.178
      port: 6379
      database: 0
      timeout: 1800s # 使用时间格式化
      password: yyccYOUyun
      lettuce:
        pool:
          max-active: 20  # 最大连接数
          max-wait: -1    # 最大阻塞等待时间(负数表示没限制)
          max-idle: 5     # 最大空闲
          min-idle: 0     # 最小空闲
  main:
    allow-bean-definition-overriding: true
    jackson:
      date-format: yyyy/MM/dd HH:mm:ss
      time-zone: GMT+8

# 登录token拦截
platform:
  interceptor:
    configs:
      exclude-login-urls:  # 非不需要登录接口
#        - /api/v1/demo/**
#        - /api/v1/file/**

      exclude-statistic-urls: # 不需要统计接口
        - /static/**
        - /icon/**
        - /css/**
  # 请求token认证接口配置
  auth:
    configs:
      enable: true
      verify-url: https://kmoa.test.oa.cnki.net/api/auth/api/v1/authentication?token=   # token 验证接口

# 必填项
spring.ai.openai.api-key: you-apikey
spring.ai.openai.base-url: https://api.deepseek.com
# 模型选择（示例使用对话模型）
spring.ai.openai.chat.options.model: deepseek-chat
#file.base.path: /data
#file.temp.path: /data/temp/
file.base.path: /home/agentweb/web/intelligent-office/backend/content/data
file.temp.path: /home/agentweb/web/intelligent-office/backend/content/data/temp/


youyun.doc.apikey: dataset-dezUJfSWgpETM8niLddTZboD
youyun.doc.create: http://10.10.93.198:8090/v1/datasets/%s/document/create-by-file   # datasetsId
youyun.doc.delete: http://10.10.93.198:8090/v1/datasets/%s/documents/%s              # datasetsId , documentId
