spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: primary
      strict: false
      datasource:
        primary:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://10.0.254.180:3306/szt-1?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&serverTimezone=Asia/Shanghai
          username: root
          password: rootlocal
  data:
    redis:
      host: 10.0.254.180
      port: 6379
      database: 0
      timeout: 1800s # 使用时间格式化
      password: szt-redis
      lettuce:
        pool:
          max-active: 20  # 最大连接数
          max-wait: -1    # 最大阻塞等待时间(负数表示没限制)
          max-idle: 5     # 最大空闲
          min-idle: 0     # 最小空闲
  task:
    execution:
      shutdown:
        await-termination: true
        await-termination-period: 60s

  main:
    allow-bean-definition-overriding: true
    jackson:
      date-format: yyyy/MM/dd HH:mm:ss
      time-zone: GMT+8

# 登录token拦截
platform:
  interceptor:
    configs:
      exclude-login-urls: # 非不需要登录接口
        - /api/v1/chat/login
        - /api/v1/chat/login/captcha
        - /api/v1/chat/login/verifyIdentityFromTfoa
        - /api/v1/chat/login/
        - /api/v1/chat/login/verifyFromTfoaMobile
        - /swagger-ui/*
        - /swagger-ui.html
        - /v3/api-docs/**
        - /webjars/**
        - /doc.html
#        - /api/v1/chat/*
#        - /api/v1/resource/*
#        - /api/v1/historyChat/*

      exclude-statistic-urls: # 不需要统计接口
        - /static/**
        - /icon/**
        - /css/**

  # 请求认证接口配置
  auth:
    configs:
      enable: true
      verify-url: https://example.com/api/auth/api/v1/authentication?token=   # token 验证接口

ai:
  answer-api: http://dify.ustack.com/v1/chat-messages
  recommend-list-api: http://127.0.0.1:18090/v1/messages/%s/suggested
  history-chat-api: http://127.0.0.1:18090/v1/messages
  conversations-chat-api: http://127.0.0.1:18090/v1/conversations
  delete-conversations-api: http://127.0.0.1:18090/v1/conversations
  person-datasets-create-api: http://127.0.0.1:18090/v1/datasets
  vector-query-api: http://127.0.0.1:18090/v1/datasets/%s/retrieve
  upload-file-api: http://127.0.0.1:18090/v1/files/upload
  datasets-document-segment-api: http://127.0.0.1:18090/v1/datasets/%s/documents/%s/segments
  datasets-delete-document-api: http://127.0.0.1:18090/v1/datasets/%s/documents/%s
  datasets-document-indexing-status-api: http://127.0.0.1:18090/v1/datasets/%s/documents/%s/indexing-status
  rename-conversation-api: http://127.0.0.1:18090/v1/conversations/%s/name
  stop-conversation-api: http://127.0.0.1:18090/v1/chat-messages/%s/stop
  chat-net-search-api: http://127.0.0.1:18090/v1/workflows/run
  data-center-chat-api: http://127.0.0.1:18090/v1/chat-messages

ragflow:
  commonUrl: http://127.0.0.1:18090/v1

# api-key
apikey:
  # 智能助手
  common: your_apikey
  # 智能代码
  intellcode: your_apikey
  # ppt大纲
  pptoutline: your_apikey
  # 新闻稿
  newsmanuscript: your_apikey
  # 智能公文
  intelldoc: app-HTY60sVjx81pTEPUjfV7i7vM
  # 智能审校
  intellproofread: your_apikey
  # 发言稿
  speechscript: your_apikey
  # 会议纪要
  meetingsammary: your_apikey
  # 数据挖掘处理
  dm: your_apikey
  # 智能研报
  intellreport: your_apikey
  # 个人知识库
  customvector: your_apikey
  # 联网搜索--暂不可用
  netsearch: your_apikey
  # 数据中台
  dataCenter: your_apikey
  # 推荐列表key
  recommendList: your_apikey
  # 意图识别
  intent: your_apikey
  # 新联网搜索  --doc没有
  newNetSearch: your_apikey
  # 意图识别-主体
  intentMain: your_apikey

datasets:
  unit-id: your_unit_id
  dep-id: your_dep_id

integration:
  rsa:
    public-key: your_public_key
    private-key: your_private_key
  ppt:
    api-key: your_apikey
    secret-key: your_apikey
    token-string-to-sign: GET@/api/grant/token/@
    token-api: https://co.aippt.cn/api/grant/token?uid=%s&channel=%s
    code-string-to-sign: GET@/api/grant/code/@
    code-api: https://co.aippt.cn/api/grant/code?uid=%s&channel=%s

# 必填项
spring.ai.openai.api-key: you-apikey
spring.ai.openai.base-url: https://api.deepseek.com
# 模型选择（示例使用对话模型）
spring.ai.openai.chat.options.model: deepseek-chat


thtf:
  ldap:
    server: ldap://example.com:389
    domain: example.com
    enable: false

xfyun:
  appId: your_appId
  apiSecret: your_apiSecret
  apiKey: your_apiKey
  lfasrSecretKey: your_lfasrSecretKey

springdoc:
  swagger-ui:
    enabled: false
  basic-auth:
    enabled: true
    username: your_username
    password: your_password
knife4j:
  enable: false
  basic:
    enable: true
    username: your_username
    password: your_password

