spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: primary
      strict: false
      datasource:
        primary:
          driver-class-name: dm.jdbc.driver.DmDriver
          url: jdbc:dm://118.193.126.254:5236/INTELLIGENT_OFFICE?schema=INTELLIGENT_OFFICE&encoding=UTF-8
          username: SYSDBA
          password: Sysdba@123
  data:
    redis:
      host: 101.52.216.178
      port: 6379
      database: 0
      timeout: 1800s # 使用时间格式化
      password: yyccYOUyun
      lettuce:
        pool:
          max-active: 20  # 最大连接数
          max-wait: -1    # 最大阻塞等待时间(负数表示没限制)
          max-idle: 5     # 最大空闲
          min-idle: 0     # 最小空闲
  task:
    execution:
      shutdown:
        await-termination: true
        await-termination-period: 60s

  main:
    allow-bean-definition-overriding: true
    jackson:
      date-format: yyyy/MM/dd HH:mm:ss
      time-zone: GMT+8





# 登录token拦截
platform:
  interceptor:
    configs:
      exclude-login-urls: # 非不需要登录接口
        - /api/v1/chat/login
        - /api/v1/chat/login/captcha
        - /api/v1/chat/login/verifyIdentityFromTfoa
        - /api/v1/chat/login/
        - /api/v1/chat/login/verifyFromTfoaMobile
        - /swagger-ui/*
        - /swagger-ui.html
        - /v3/api-docs/**
        - /webjars/**
        - /doc.html
#        - /api/v1/chat/*
#        - /api/v1/resource/*
#        - /api/v1/historyChat/*

      exclude-statistic-urls: # 不需要统计接口
        - /static/**
        - /icon/**
        - /css/**

  # 请求认证接口配置
  auth:
    configs:
      enable: true
      verify-url: https://kmoa.test.oa.cnki.net/api/auth/api/v1/authentication?token=   # token 验证接口

ai:
  answer-api: http://119.254.155.240:18090/v1/chat-messages
  recommend-list-api: http://119.254.155.240:18090/v1/messages/%s/suggested
  history-chat-api: http://119.254.155.240:18090/v1/messages
  conversations-chat-api: http://119.254.155.240:18090/v1/conversations
  delete-conversations-api: http://119.254.155.240:18090/v1/conversations
  person-datasets-create-api: http://119.254.155.240:18090/v1/datasets
  vector-query-api: http://119.254.155.240:18090/v1/datasets/%s/retrieve
  #  cnki-vector-query-api: https://maas.cnki.net/maas-gateway/cnkisearch
  upload-file-api: http://119.254.155.240:18090/v1/files/upload
  datasets-document-segment-api: http://119.254.155.240:18090/v1/datasets/%s/documents/%s/segments
  datasets-delete-document-api: http://119.254.155.240:18090/v1/datasets/%s/documents/%s
  datasets-document-indexing-status-api: http://119.254.155.240:18090/v1/datasets/%s/documents/%s/indexing-status
  rename-conversation-api: http://119.254.155.240:18090/v1/conversations/%s/name
  stop-conversation-api: http://119.254.155.240:18090/v1/chat-messages/%s/stop
  chat-net-search-api: http://119.254.155.240:18090/v1/workflows/run
  data-center-chat-api: http://119.254.155.240:18090/v1/chat-messages


# api-key
apikey:
  # 智能助手
  common: app-3P4HVPVeoNl6L1ZhUZl2evQl
  # 智能代码
  intellcode: app-MF0v0yXl3s33wPVaepsvBVMc
  # ppt大纲
  pptoutline: app-KWgDvVooc0zskI0eY7DyrbIU
  # 新闻稿
  newsmanuscript: app-oSzsdmDdC3O9g6zBR6yhuORK
  # 智能公文
  intelldoc: app-z1ev8jWWWq0VOpCIFkHCsSEc
  # 智能审校
  intellproofread: app-z8Hrj4mj3X3uGVnGIjcrU1pb
  # 发言稿
  speechscript: app-uZ0x3XaSyB0D4yaxS4iraOhS
  # 会议纪要
  meetingsammary: app-0rboba0jQweVfdES4dmt3JJw
  # 数据挖掘处理
  dm: app-7MlA0qIGe9CZUIXKP8JHyiBH
  # 智能研报
  intellreport: app-yWYyVMfDmq0us7al5bg7JVYG
  # 个人知识库
  customvector: dataset-kNfh2qv11cCdKv1yg9JjEctT
  # 联网搜索--暂不可用
  netsearch: app-q6PgQfNd13N26n5d2Rckjt4k
  # 数据中台
  dataCenter: app-TQ4J8MMGB2iQmF3infBr14cp
  # 推荐列表key
  recommendList: app-ONOtPOsaMB2Gzdmj8eBVhEKH
  # 意图识别
  intent: app-ZloxQh9n6H6ztIa4n96qKKIj
  # 新联网搜索  --doc没有
  newNetSearch: sk-5d336986887b474ca4c7f37ab3731f44
  # 意图识别-主体
  intentMain: app-ir26ZHxTOltaUpLX2ofEjT9A

datasets:
  unit-id: e811be65-ef5c-4cec-aa83-8f0401fa6947
  #  dep-id: f6456a92-2497-4abd-bdbc-9e58f21bf7e7
  dep-id: 09c749d3-7dca-435c-bb84-3610921ef3ed

integration:
  rsa:
    public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjERtGXLscEUZHixkx6NbYpRo+RPjIUmjIUNPLwk0LaPd8tb2ggUmqElJWBUTfY0bdXv4A174ZigXrK9X8MoC+jvuTN1h4y4OTxjyoAJaV6HivaQy7XLUAWihWOhAT6IRg2N1xu+rwywvmNNePvcv6IwKHoCojkXFCCdjky4fd5tL7QJbQ2lZUcuTNv+nWFbxUUWdxOIv2gHHX1c6MlJJ3PRiLEgLe5BfD0XOI8FBHKcjT6wg5C5j/7EDeFrAtpb96FrcQNAYBiBSClR0RVmXOLBo3zHF+tZ/TmZTQWs00Uj+HGispNOb6D35sfjdKclKPHLOtgn++SwV2eHkjuKEBwIDAQAB
    private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCMRG0ZcuxwRRkeLGTHo1tilGj5E+MhSaMhQ08vCTQto93y1vaCBSaoSUlYFRN9jRt1e/gDXvhmKBesr1fwygL6O+5M3WHjLg5PGPKgAlpXoeK9pDLtctQBaKFY6EBPohGDY3XG76vDLC+Y014+9y/ojAoegKiORcUIJ2OTLh93m0vtAltDaVlRy5M2/6dYVvFRRZ3E4i/aAcdfVzoyUknc9GIsSAt7kF8PRc4jwUEcpyNPrCDkLmP/sQN4WsC2lv3oWtxA0BgGIFIKVHRFWZc4sGjfMcX61n9OZlNBazTRSP4caKyk05voPfmx+N0pyUo8cs62Cf75LBXZ4eSO4oQHAgMBAAECggEAB4hH0OK1A7USNjvtZYhw3d2uYsHIo/76UvefBvLtlGMvsLIOfB5JXHwjA3yOQWMUeGih1ucrW6uyKcR4v9DOpsq/xJeW1sZLCmsCjHPT5M99XPBhCRNDg0KFIkBxQ6rRBJyQtJAmSc1+TiymQPyxMUG5QWNoqcs2sMtnXiikk/L0mkN+ZA/9FPq2MArJjpAi8ayoGynnmcI1owzfaTTn/LrEtUPu+iLV6f5ckvQPbe41g5VjTsp+UbQFcc9AbLOaoldvtY3xjg1ah2DYVNfMfJcXxj4EVYzbMCgjjDWiLyaXeASwvcGOMazcyZfjFcjimeJPAJr3SPY6gx7ACoje4QKBgQDGEP7uIOEnV47A7z12Wy/YtJFyzN/yNBc0YPKy6M0PeCWP19djDWd1F3hzDffswKtm5X12iEHrw2M9qoQ+9t93ktVST+IOaW7f306nSQjNmT0LFRCPJLQGZTTIpO1MCiKLW5ZFmHvdfUtTE1jB67Rmwx9YMGNVoqI3Y/9j6w/9bwKBgQC1S36BSs2OMPQwf3StttvSHZTbTmA3E9FN5SODTg5ISiE0k4hal6LGmqAFZcFlrB8tUu/AmtW+ARFc06exbAOcmMcZXOceg2kAirLM0HeuGTOFjfa9cFsoGDuyvTAYogtX8KyFnY+QZ4Zg5oqfaaGjgLpZ8OwQfXdVgyD5rz/G6QKBgAEz7Tho/rUMdRN64HatixbX0eJOmDWSV2m8BP1NKKGlayT6fJZfaHdvkw2v0gegC+puDlr/7NaPszSWqoLvYOALBjyfu5G21jOJ2aJucR0+hv5gPF+CK422Y6GsTrydeyQ5hCocCPSJZEG25l0XH1tYaAJTGOdWO4H2m4Bx1wEFAoGBAJILQNtyoOhcszmmUx3lYmt+/P01w/hadI+leNg7tvGxFdK+zmb8JFqNET+H2yXGZE8kspKbqHepcI0wy7P3aWlrAWiDGIPSJHIVSTgI74BGOOTrmcq9ihFghCbWlLojP7QV40S3yoDvhKbm0ODePSHzfysZE3GtQMaYHaZF8MCRAoGBAMEZrp/j6k7M5p9rApoeseibZ1/JDTboYmpW0J2lTFMlhktMnd820wHj6R/HcsWEn9Bas9pHJq4kW82SqGeGTnHwRHB7O/84dCfSAOHTHK5c8XJE2NW+wgkpFLeCsuJI4BTJXHoeonsjhU9xlJ4498fzbfDUN0pFI4HJ3qsEy81T
  thtf:
    pc-redirect-url: http://10.10.93.76/authorization
    h5-redirect-url: http://10.10.93.76/h5/authorization
  ppt:
    api-key: 67caa0869255a
    secret-key: v6kBne1Kl1vQVlvuK3ck1tEsVD8lbSZs
    token-string-to-sign: GET@/api/grant/token/@
    token-api: https://co.aippt.cn/api/grant/token?uid=%s&channel=%s
    code-string-to-sign: GET@/api/grant/code/@
    code-api: https://co.aippt.cn/api/grant/code?uid=%s&channel=%s

cnki:
  vector:
    access-key: bc3e6f71963f430bab868284062ab9bd
    secret-key: cd182fb37ff34effaec1424e6c65482b

# 必填项
spring.ai.openai.api-key: you-apikey
spring.ai.openai.base-url: https://api.deepseek.com
# 模型选择（示例使用对话模型）
spring.ai.openai.chat.options.model: deepseek-chat


thtf:
  ldap:
    server: ldap://thtf.com:389
    domain: thtf.com
    enable: false

xfyun:
  appId: cf4efd43
  apiSecret: MjgzNGQ4MDc5YzA4MzIwZjAyY2JmMzQ5
  apiKey: c30b33e9efe1b01db0e3552ec1eb14e2
  lfasrSecretKey: a6e0fdd91908e24e712e19a47dd19aa2

springdoc:
  swagger-ui:
    enabled: true
  basic-auth:
    enabled: true
    username: ttkn
    password: ttkn_doc@2025
knife4j:
  enable: true
  basic:
    enable: true
    username: ttkn
    password: ttkn_doc@2025


